### ISSUE TITLE
Avoid hardcoded ELPA package paths in recommended setup?

### ISSUE THREAD

**Issue by NateEag** [tarsius/auto-compile#11]
The recommended setup block includes this:

```elisp
(add-to-list 'load-path "/path/to/dash")
(add-to-list 'load-path "/path/to/packed")
(add-to-list 'load-path "/path/to/auto-compile")
(require 'auto-compile)
```

but if those libraries have been installed via `package.el`, they're all in the ELPA dir, so something like

```elisp
(let ((default-directory "~/.emacs.d/elpa/"))
  (normal-top-level-add-subdirs-to-load-path))
(require 'auto-compile)
```

works, and avoids hardcoded paths that need to be changed when one of the dependencies gets updated (since package.el includes datestamps in package directory names).

My setup does result in `load-path` having all the ELPA directories twice, but AFAIK that has no significant negative consequences. In principle loading packages is slower, but I doubt it makes much difference.

I've been handling it this way for ages and meant to mention this a while ago - just happened to remember and have some free time for once this afternoon.

**Comment by tarsius** [comment]
I think there can be multiple versions per package inside the elpa directory. If that is so, then adding all subdirectories might result in the wrong version being placed earlier on the `load-path`. Also it is possible to disable some packages using `package-load-list` and we wouldn't want to add the disabled packages to the `load-path` either.

After reading parts of `package.el`s activation code I think it is safe to call `package-initialize` before enabling enabling `auto-compile-on-load-mode`, because, as far as I can tell, the only files that are being loaded during that step are the autoload files (and these aren't byte-compiled anyway).

I have updated the instructions accordingly.
