### ISSUE TITLE
Mention that dash is a requirement in the README

### ISSUE THREAD

**Issue by caleb** [tarsius/auto-compile#8]
Mention that `dash` is a requirement along with `packed` in the README.

I saw that you are want to integrate auto-compile into `prelude`, I'm looking forward to that!

**Comment by tarsius** [comment]
No, I don't think I should have to mention that.

When using `package.el` to install then that is being taken care of anyway. When not using a package manager, but e.g. git submodules (like I do) then you have to get into a habit of grepping for `(require '` anyway.

It would be a different story if `dash` weren't a general purpose library. But it actually is a library with "utilities we had to implement, because they are still missing from Emacs". If the dependency were closely related to what this package does, then it probably should be mentioned.

So it's a bit strange you did not mention `packed` which while only moderately related still is more related to `auto-compile` than `dash`. But still not enough for me to want to mention it at this point. (This might change when I next make substantial changes to these packages, but not before then).

**Comment by caleb** [comment]
I only mention it because I thought that you were supposed to load auto-compile before package.el etc so it get's loaded as early as possible. So while I used `package.el` (from prelude), I thought it was best to put auto-compile in as early as possible in my configuration.

I didn't mention `packed` because it is listed in the installation instructions under `Setup` which I followed to get `auto-compile` working. I used the sample code from the Setup section and ran into problems because dash was not loaded.

```
;;; init.el --- user init file      -*- no-byte-compile: t -*-
(setq load-prefer-newer t)
(add-to-list 'load-path "/path/to/packed")
(add-to-list 'load-path "/path/to/auto-compile")
(require 'auto-compile)
(auto-compile-on-load-mode 1)
(auto-compile-on-save-mode 1)
```

**Comment by tarsius** [comment]
Oh! Yes, that's right. Will fix.

**Comment by caleb** [comment]
Sorry for the incredibly terse bug report initially. That is very much unlike me, and I'm usually fairly thorough. Looking back it's a pretty terrible bug report :)

**Comment by tarsius** [comment]
Thought so too, but then I should just have asked for clarification :-)

**Comment by tarsius** [comment]
Fixed. Thanks for pointing this out.
